// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBUZ7lujAbAMUwBLhnUZhx1nVExDeoPBw',
    appId: '1:472833283384:web:ee449e8b7a4f336df8ddcd',
    messagingSenderId: '472833283384',
    projectId: 'connectpamodziv03',
    authDomain: 'connectpamodziv03.firebaseapp.com',
    databaseURL: 'https://connectpamodziv03-default-rtdb.firebaseio.com',
    storageBucket: 'connectpamodziv03.appspot.com',
    measurementId: 'G-Y7Y0S9JG6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSUoD0wnyq26_6eQPxbD99m35LL1jksCk',
    appId: '1:472833283384:android:5eee069813b5b1def8ddcd',
    messagingSenderId: '472833283384',
    projectId: 'connectpamodziv03',
    databaseURL: 'https://connectpamodziv03-default-rtdb.firebaseio.com',
    storageBucket: 'connectpamodziv03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBNjzn4eYXzFrs-kwjN-JERad4kbBSYMU',
    appId: '1:472833283384:ios:0e37f9a71a7bf2adf8ddcd',
    messagingSenderId: '472833283384',
    projectId: 'connectpamodziv03',
    databaseURL: 'https://connectpamodziv03-default-rtdb.firebaseio.com',
    storageBucket: 'connectpamodziv03.appspot.com',
    iosClientId: '472833283384-gdkgirktnlvbakhherjf39rqap8snnil.apps.googleusercontent.com',
    iosBundleId: 'com.robinwarden.fluttershare',
  );
}
